In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("../data/movies.csv")
ratings = pd.read_csv("../data/ratings.csv")
tags = pd.read_csv("../data/tags.csv")
links = pd.read_csv("../data/links.csv")
credits = pd.read_csv("../data/credits.csv")
keywords = pd.read_csv("../data/keywords.csv")
tmdb = pd.read_csv("../data/tmdb_5000_movies.csv")

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62423 entries, 0 to 62422
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  62423 non-null  int64
 1   title    62423 non-null  object
 2   genres   62423 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB

In [5]:
movies.shape

(62423, 3)

In [6]:
movies.describe(include="all")

              movieId            title genres
count    62423.000000            62423  62423
unique            NaN            62325   1639
top               NaN  The Void (2016)  Drama
freq              NaN                2   9056
mean    122220.387646              NaN    NaN
std      63264.744844              NaN    NaN
min          1.000000              NaN    NaN
25%      82146.500000              NaN    NaN
50%     138022.000000              NaN    NaN
75%     173222.000000              NaN    NaN
max     209171.000000              NaN    NaN

In [7]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [8]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000095 entries, 0 to 25000094
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 762.9 MB